server:
  port: ${PORT:8010}
spring:
  application:
    name: service1
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
      
